<a href="https://colab.research.google.com/github/AudryBarimbane/mlzoomcamp/blob/main/09_tensorflow_lite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%autosave 0

Autosave disabled


In [2]:
import tensorflow as ft
from tensorflow import keras

In [3]:
!wget https://github.com/alexeygrigorev/mlbookcamp-code/releases/download/chapter7-model/xception_v4_large_08_0.894.h5  -O clothing-model.h5

--2021-12-01 16:55:08--  https://github.com/alexeygrigorev/mlbookcamp-code/releases/download/chapter7-model/xception_v4_large_08_0.894.h5
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/256401220/0156a400-0049-11eb-8490-c0d01b48ea8c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20211201%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211201T165508Z&X-Amz-Expires=300&X-Amz-Signature=84ccf9d9b431dd897d599f0125682a9e739ce5be72561223d87071332d799994&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=256401220&response-content-disposition=attachment%3B%20filename%3Dxception_v4_large_08_0.894.h5&response-content-type=application%2Foctet-stream [following]
--2021-12-01 16:55:08--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/25640

In [4]:
!python -V

Python 3.7.12


In [5]:
import tensorflow as tf
from tensorflow import keras 
tf.__version__

'2.7.0'

In [6]:
#use keras models module to load the model
model = keras.models.load_model('clothing-model.h5')

In [7]:
!wget http://bit.ly/mlbookcamp-pants -O pants.jpeg

--2021-12-01 16:55:11--  http://bit.ly/mlbookcamp-pants
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/alexeygrigorev/clothing-dataset-small/master/test/pants/4aabd82c-82e1-4181-a84d-d0c6e550d26d.jpg [following]
--2021-12-01 16:55:11--  https://raw.githubusercontent.com/alexeygrigorev/clothing-dataset-small/master/test/pants/4aabd82c-82e1-4181-a84d-d0c6e550d26d.jpg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23048 (23K) [image/jpeg]
Saving to: ‘pants.jpeg’

pants.jpeg          100%[===================>]  22.51K  --.-KB/s    in 0.001s  

2021-12-01 16:55:11 (16.5 MB/s) - ‘pants.j

In [8]:
#reading images 
from tensorflow.keras.preprocessing.image import  load_img
from tensorflow.keras.applications.xception import preprocess_input

In [9]:
#loading image with size of 299, 299
img = load_img('pants.jpeg',target_size=(299,299))

In [10]:
import numpy as np

In [11]:
x = np.array(img)
X = np.array([x])

X = preprocess_input(X)

In [12]:
X

array([[[[-0.11372548, -0.15294117, -0.19999999],
         [-0.11372548, -0.15294117, -0.19999999],
         [-0.10588235, -0.14509803, -0.19215685],
         ...,
         [-0.01960784, -0.01960784, -0.08235294],
         [-0.04313725, -0.04313725, -0.10588235],
         [-0.11372548, -0.11372548, -0.17647058]],

        [[-0.09019607, -0.12941176, -0.17647058],
         [-0.09019607, -0.12941176, -0.17647058],
         [-0.08235294, -0.12156862, -0.16862744],
         ...,
         [-0.01960784, -0.01960784, -0.08235294],
         [-0.04313725, -0.04313725, -0.10588235],
         [-0.10588235, -0.10588235, -0.16862744]],

        [[-0.09803921, -0.1372549 , -0.18431371],
         [-0.09803921, -0.1372549 , -0.18431371],
         [-0.09019607, -0.12941176, -0.17647058],
         ...,
         [-0.01960784, -0.01960784, -0.08235294],
         [-0.03529412, -0.03529412, -0.09803921],
         [-0.09019607, -0.09019607, -0.15294117]],

        ...,

        [[-0.67058825, -0.7019608 , -0

In [13]:
X.shape

(1, 299, 299, 3)

In [14]:
preds = model.predict(X)

In [15]:
preds

array([[-1.8682904, -4.7612443, -2.3169835, -1.0625707,  9.887159 ,
        -2.812435 , -3.6662824,  3.2003615, -2.6023388, -4.835046 ]],
      dtype=float32)

In [16]:
classes = [
    'dress',
    'hat',
    'longsleeve',
    'outwear',
    'pants',
    'shirt',
    'shoes',
    'shorts',
    'skirt',
    't-shirt'
]

In [17]:
dict(zip(classes, preds[0]))

{'dress': -1.8682904,
 'hat': -4.7612443,
 'longsleeve': -2.3169835,
 'outwear': -1.0625707,
 'pants': 9.887159,
 'shirt': -2.812435,
 'shoes': -3.6662824,
 'shorts': 3.2003615,
 'skirt': -2.6023388,
 't-shirt': -4.835046}

##Convert Keras to TF-Lite

In [18]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open('clothing-model.tflite','wb') as f_out:
  f_out.write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpv4c70ob4/assets


In [19]:
!ls -lh 

total 325M
-rw-r--r-- 1 root root  83M Aug 17 10:47 clothing-model.h5
-rw-r--r-- 1 root root  81M Dec  1 15:40 clothing_model.tflite
-rw-r--r-- 1 root root  81M Dec  1 16:55 clothing-model.tflite
-rw-r--r-- 1 root root  23K Dec  1 16:55 pants.jpeg
drwxr-xr-x 1 root root 4.0K Nov 18 14:36 sample_data
-rw-r--r-- 1 root root  83M Aug 17 10:47 xception_v4_large_08_0.894.h5


In [20]:
import tensorflow.lite as tflite 

In [21]:
interpreter = tflite.Interpreter(model_path='clothing-model.tflite')
interpreter.allocate_tensors()

In [22]:
interpreter.get_input_details()

[{'dtype': numpy.float32,
  'index': 0,
  'name': 'serving_default_input_8:0',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([  1, 299, 299,   3], dtype=int32),
  'shape_signature': array([ -1, 299, 299,   3], dtype=int32),
  'sparsity_parameters': {}}]

In [23]:
input_index = interpreter.get_input_details()[0]['index']


In [24]:
interpreter.get_output_details()

[{'dtype': numpy.float32,
  'index': 229,
  'name': 'StatefulPartitionedCall:0',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 10], dtype=int32),
  'shape_signature': array([-1, 10], dtype=int32),
  'sparsity_parameters': {}}]

In [25]:
output_index = interpreter.get_output_details()[0]['index']

In [26]:
interpreter.set_tensor(input_index, X)

In [27]:
interpreter.invoke()

In [28]:
preds = interpreter.get_tensor(output_index)

In [29]:
classes = [
    'dress',
    'hat',
    'longsleeve',
    'outwear',
    'pants',
    'shirt',
    'shoes',
    'shorts',
    'skirt',
    't-shirt'
]

In [30]:
dict(zip(classes, preds[0]))

{'dress': -1.8682897,
 'hat': -4.761245,
 'longsleeve': -2.316984,
 'outwear': -1.0625701,
 'pants': 9.8871565,
 'shirt': -2.8124309,
 'shoes': -3.6662824,
 'shorts': 3.2003605,
 'skirt': -2.6023393,
 't-shirt': -4.835046}

##Removing TF dependency

In [31]:
from PIL import Image

In [32]:
with Image.open('pants.jpeg') as img:
  img = img.resize((299,299), Image.NEAREST)

In [33]:
def preprocess_input(x):
  x /= 127.5
  x -= 1.
  return x




In [34]:
img = load_img('pants.jpeg',target_size=(299, 299))

x = np.array(img, dtype='float32')
X = np.array([x])

X = preprocess_input(X)


In [35]:
interpreter.set_tensor(input_index, X)
interpreter.invoke()
preds = interpreter.get_tensor(output_index)

In [36]:
classes = [
    'dress',
    'hat',
    'longsleeve',
    'outwear',
    'pants',
    'shirt',
    'shoes',
    'shorts',
    'skirt',
    't-shirt'
]
dict(zip(classes, preds[0]))


{'dress': -1.8682897,
 'hat': -4.761245,
 'longsleeve': -2.316984,
 'outwear': -1.0625701,
 'pants': 9.8871565,
 'shirt': -2.8124309,
 'shoes': -3.6662824,
 'shorts': 3.2003605,
 'skirt': -2.6023393,
 't-shirt': -4.835046}

##Simple way to do it 

In [37]:
!pip install keras-image-helper

In [38]:
from keras_image_helper import  create_preprocessor

In [39]:
preprocessor = create_preprocessor('xception', target_size=(299, 299))

In [40]:
url = 'http://bit.ly/mlbookcamp-pants '
X = preprocessor.from_url(url)

In [41]:
X

array([[[[-0.11372548, -0.15294117, -0.19999999],
         [-0.11372548, -0.15294117, -0.19999999],
         [-0.10588235, -0.14509803, -0.19215685],
         ...,
         [-0.01960784, -0.01960784, -0.08235294],
         [-0.04313725, -0.04313725, -0.10588235],
         [-0.11372548, -0.11372548, -0.17647058]],

        [[-0.09019607, -0.12941176, -0.17647058],
         [-0.09019607, -0.12941176, -0.17647058],
         [-0.08235294, -0.12156862, -0.16862744],
         ...,
         [-0.01960784, -0.01960784, -0.08235294],
         [-0.04313725, -0.04313725, -0.10588235],
         [-0.10588235, -0.10588235, -0.16862744]],

        [[-0.09803921, -0.1372549 , -0.18431371],
         [-0.09803921, -0.1372549 , -0.18431371],
         [-0.09019607, -0.12941176, -0.17647058],
         ...,
         [-0.01960784, -0.01960784, -0.08235294],
         [-0.03529412, -0.03529412, -0.09803921],
         [-0.09019607, -0.09019607, -0.15294117]],

        ...,

        [[-0.67058825, -0.7019608 , -0

In [42]:
interpreter.set_tensor(input_index, X)
interpreter.invoke()
preds = interpreter.get_tensor(output_index)

In [43]:
classes = [
    'dress',
    'hat',
    'longsleeve',
    'outwear',
    'pants',
    'shirt',
    'shoes',
    'shorts',
    'skirt',
    't-shirt'
]
dict(zip(classes, preds[0]))

{'dress': -1.8682897,
 'hat': -4.761245,
 'longsleeve': -2.316984,
 'outwear': -1.0625701,
 'pants': 9.8871565,
 'shirt': -2.8124309,
 'shoes': -3.6662824,
 'shorts': 3.2003605,
 'skirt': -2.6023393,
 't-shirt': -4.835046}